language: node_js
node_js:
- node

cache:
  directories:
    - node_modules

deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: yaggarwa/tambrefresh
  bucket: mytamb-bucket02
  region: us-east-2

- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: mytamb-bucket02
  key: latest.zip
  bundle_type: zip
  application: tambdeploy
  deployment_group: mycodedeploygroup
  region: us-east-2
  on: *2

script:
  - unset CI 
  - npm run build
  - zip -r latest * -x node_modules/
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip
