version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ubuntu/tamb2.0
BeforeInstall:
  - location: scripts/prepare_env.sh
    timeout: 300
    runas: root
AfterInstall:
  - location: scripts/after_install.sh
  - location: scripts/stop_previous_instance.sh
    timeout: 300
    runas: root
ApplicationStart:
  - location: scripts/start_server.sh
    timeout: 300
    runas: root
